image:
  - Visual Studio 2017

platform:
  - x86
  - x64

environment:
  matrix:
    - CONFIG: Release
    - CONFIG: Debug

install:
  - |
    set THIRD_DIR=%APPVEYOR_BUILD_FOLDER%\3rd
    mkdir %THIRD_DIR% && cd %THIRD_DIR%
    curl -sSL -O https://github.com/log4cplus/log4cplus/archive/REL_1_2_0.zip
    7z x REL_1_2_0.zip
    cd log4cplus-REL_1_2_0 && mkdir build && cd build
    if "%PLATFORM%"=="x86" set generator=Visual Studio 15 2017
    if "%PLATFORM%"=="x64" set generator=Visual Studio 15 2017 Win64
    cmake -G "%generator%" -DCMAKE_CONFIGURATION_TYPES=%CONFIG% -D_WIN32_WINNT=0x0601 -DUNICODE=OFF -DLOG4CPLUS_BUILD_TESTING=OFF -DLOG4CPLUS_BUILD_LOGGINGSERVER=OFF ..
    cmake --build . --config %CONFIG%
    set PATH=%PATH%;%THIRD_DIR%\log4cplus-REL_1_2_0\build\bin\%CONFIG%
    cd %THIRD_DIR%
    mkdir otl && cd otl && curl -sS -O http://otl.sourceforge.net/otlv4_h2.zip && 7z x otlv4_h2.zip

before_build:
  - |
    cd %APPVEYOR_BUILD_FOLDER% && mkdir build && cd build
    if "%PLATFORM%"=="x86" set boost_lib_path=C:\Libraries\boost_1_67_0\lib32-msvc-14.1
    if "%PLATFORM%"=="x64" set boost_lib_path=C:\Libraries\boost_1_67_0\lib64-msvc-14.1
    cmake -G "%generator%" -DCMAKE_CONFIGURATION_TYPES=%CONFIG% -DBOOST_INCLUDEDIR=C:\Libraries\boost_1_67_0 -DBOOST_LIBRARYDIR=%boost_lib_path% -Dlog4cplus_INCLUDEDIR=%APPVEYOR_BUILD_FOLDER%\3rd\log4cplus-REL_1_2_0\include\ -Dlog4cplus_LIBRARYDIR=%APPVEYOR_BUILD_FOLDER%\3rd\log4cplus-REL_1_2_0\build\src\ -Dotl_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%\3rd\ -Dotl_VERSION_MAJOR=4 ..

build_script:
  - cmake --build . --config %CONFIG% && ctest --build-config %CONFIG% --output-on-failure