language: cpp

os:
  - linux

dist: trusty
sudo: required

compiler:
  - clang
  - gcc

env:
  matrix:
    - CONFIG=Release
    - CONFIG=Debug

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      sudo apt-get update -qq
    else
      brew update
    fi

install:
  - THIRD_DIR="$TRAVIS_BUILD_DIR/3rd"
  - |
    if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      sudo apt-get -qq install -y unzip libbsd-dev
      mkdir $THIRD_DIR
      cd $THIRD_DIR
      wget --no-check-certificate --quiet https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2
      tar xjf ./boost_1_66_0.tar.bz2 && cd ./boost_1_66_0/ && ./bootstrap.sh
      ./bjam stage --toolset=$CC cflags="-fPIC" cxxflags="-std=c++11 -fPIC" linkflags="-fPIC" --with-system --with-thread --with-regex --with-filesystem --with-program_options --with-atomic --with-date_time --with-test --stagedir="./stage" link=static runtime-link=shared threading=multi --layout=versioned variant=$(tr 'A-Z' 'a-z'<<<"$CONFIG")
      wget --no-check-certificate --quiet https://github.com/log4cplus/log4cplus/archive/REL_1_2_0.zip
      unzip -q REL_1_2_0.zip
      cd log4cplus-REL_1_2_0 && mkdir build && cd build
      cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_CXX_FLAGS="-std=c++11" -DLOG4CPLUS_BUILD_TESTING=OFF -DLOG4CPLUS_BUILD_LOGGINGSERVER=OFF ..
      make && sudo make install && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
      cd $THIRD_DIR
      mkdir otl && cd otl && wget -q http://otl.sourceforge.net/otlv4_h2.zip && unzip -q otlv4_h2.zip
      cd $TRAVIS_BUILD_DIR
    else
      brew upgrade cmake || brew install cmake
      brew install boost log4cplus
      mkdir $THIRD_DIR && cd $THIRD_DIR
      curl -O https://github.com/JackieXie168/libbsd/archive/0.8.3-macosx.zip
      unzip -q 0.8.3-macosx.zip
      cd libbsd-0.8.3-macosx
      ./autogen && ./configure && make && make install
    fi
  - cmake --version

before_script:
  - mkdir build
  - cd ./build
  - if [[ "$CXX" = "g++" && "$CONFIG" = "Debug" && "$TRAVIS_OS_NAME" = "linux" ]]; then export COVERAGE_FLAGS="--coverage"; fi
  - cmake -Dotl_INCLUDEDIR=$TRAVIS_BUILD_DIR/3rd -Dotl_VERSION_MAJOR=4 -DCMAKE_CXX_FLAGS="$COVERAGE_FLAGS" -DBOOST_INCLUDEDIR="$THIRD_DIR/boost_1_66_0" -DBOOST_LIBRARYDIR="$THIRD_DIR/boost_1_66_0/stage/lib" -DCMAKE_BUILD_TYPE=$CONFIG ..

script:
  - sudo env "PATH=$PATH" cmake --build . --target install && ctest --output-on-failure

after_success:
  - if [[ "$CXX" = "g++" && "$CONFIG" = "Debug" && "$TRAVIS_OS_NAME" = "linux" ]]; then chmod +x ../coveralls && ../coveralls; fi